DFSJKOHhjkafdsjh
This is what happens when you use software that has been abandoned for 7 years

diff --git a/.github/workflows/minify.yml b/.github/workflows/minify.yml
--- a/.github/workflows/minify.yml
+++ b/.github/workflows/minify.yml
@@ -38,19 +38,12 @@ jobs:
           git checkout main -- .
           git reset HEAD
 
-      - name: Does luamin even exist? Does it find the files?
-        run: |
-          which luamin
-          luamin --version
-          echo "gug"
-          find . -name "*.lua" -not -path "./.git/*"
-
-
       - name: Minify all Lua files
         run: |
           set -e
           for file in $(find . -name "*.lua" -not -path "./.git/*"); do
-            luamin -f "$file" > "$file.min"
+            luamin -f "$file" > "$file.min" || true
+            # For some stupid fucking reason, luamin returns exit code 1
             mv "$file.min" "$file"
           done
 
